services:
  - type: web
    name: kas-gc3k
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn kas_gc3k.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:QnRPWwikGkSSISFVJwVSsrSckYXUzFqU@switchback.proxy.rlwy.net:14973/railway