# Generated by Django 5.2.3 on 2025-06-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blok', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sudah', 'Sudah Ditempati'), ('segera', 'Segera Ditempati'), ('belum', 'Belum Ditempati')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('bulan', models.CharField(max_length=20)),
                ('iuran_sampah', models.IntegerField(default=0)),
                ('iuran_dansos', models.IntegerField(default=0)),
                ('rumah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kas.rumah')),
            ],
            options={
                'unique_together': {('rumah', 'tahun', 'bulan')},
            },
        ),
    ]
