# Generated by Django 5.2.3 on 2025-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('nominal', models.PositiveIntegerField()),
                ('keterangan', models.CharField(max_length=255)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
