# Generated by Django 5.2.3 on 2025-07-03 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0002_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
